// <auto-generated />
using System;
using HexagonalArchitecture.Adapter.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HexagonalArchitecture.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    partial class HexagonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HexagonalArchitecture.Adapter.Persistence.EntityFramework.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthOn")
                        .HasColumnType("date")
                        .HasColumnName("BIRTH_ON");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("EMAIL_ADDRESS");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("CUSTOMERS");
                });

            modelBuilder.Entity("HexagonalArchitecture.Adapter.Persistence.EntityFramework.CustomerModel", b =>
                {
                    b.OwnsOne("HexagonalArchitecture.Adapter.Persistence.EntityFramework.AddressModel", "Address", b1 =>
                        {
                            b1.Property<int>("CustomerModelId")
                                .HasColumnType("int");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("CITY_NAME");

                            b1.Property<string>("CountryName")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("COUNTRY_NAME");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("varchar(20)")
                                .HasColumnName("POSTAL_CODE");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("STREET_NAME");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("varchar(20)")
                                .HasColumnName("STREET_NUMBER");

                            b1.HasKey("CustomerModelId");

                            b1.ToTable("CUSTOMERS");

                            b1.WithOwner()
                                .HasForeignKey("CustomerModelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
